kind: ConfigMap
apiVersion: v1
metadata:
  name: default-clusterscanprofiles
  namespace: {{ template "cis.namespace" . }}
data:
  # Default ClusterScanProfiles per cluster provider type
  rke: |-
    <1.21.0: rke-profile-permissive-1.20
    >=1.21.0: rke-profile-permissive-1.8
  rke2: |-
    <1.21.0: rke2-cis-1.20-profile-permissive
    >=1.21.0: rke2-cis-1.10-profile
  eks: "eks-profile-1.5.0"
  gke: "gke-profile-1.6.0"
  aks: "aks-profile"
  k3s: "k3s-cis-1.10-profile"
  default: "cis-1.10-profile"
